name = "t06-plandoc-diary"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "t06-plandoc-diary-db"
database_id = "b0ae5ea1-52d8-4a37-bc90-0cf6fb317cc3"
